version: "3.9"

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: express-backend
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    ports:
      - "5001:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app          # Mount local backend for hot reload
      - /usr/src/app/node_modules       # Keep container node_modules separate
    stdin_open: true
    tty: true
    command: npm run dev                # Make sure you have nodemon installed
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules       # Keep container node_modules separate
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    depends_on:
      - backend
    command: npm start
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
